name: project
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_naver_map:
  geocoding: ^2.0.4
  cupertino_icons: ^1.0.2
  get:
  http:
  flutter_native_splash: ^2.0.5
  flutter_launcher_icons: ^0.13.1
  table_calendar: ^3.0.0
  intl:
  dio:
  fluttertoast:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/instagram.png
    - assets/images/recall_splash.png
